Revert "Set Fuchsia WLAN tests to use policy as default"
This reverts commit a30b41488fd90d1daa70944a11ae09a100a48ff3.

Reason for revert: Looks like it's breaking any test that uses a fuchsia_device:

[Fuchsia_testbed_with_access_point] 2020-11-23 11:27:56.346 INFO ==========> Sl4fSanityTest <========== [base_test.py:run:767]
[Fuchsia_testbed_with_access_point] 2020-11-23 11:28:00.048 INFO [FuchsiaDevice | fe80::c940:7db4:db33:10c8%enx00e04c000bbc] sl4f.cmx has not started yet. Waiting 1 second and checking again. ...

"/home/karthikrish/tools/test/connectivity/acts/framework/acts/controllers/fuchsia_device.py", line 1236, in remove_and_preserve_networks_and_client_state
    raise FuchsiaDeviceError(
acts.controllers.fuchsia_device.FuchsiaDeviceError: Failed to get preexisting saved networks: Get saved networks: fidl error ClientWrite(Status(PEER_CLOSED))

Change-Id: Ie7ddd8d38724825c63964f231c76d19b5deae188